In [ ]:
import numpy as np

array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
array2=np.array([[11,12,13],[14,15,16],[17,18,19]])
print(array2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [ ]:
resultarray=array1-array2
print("\nusing operator:\n",resultarray)
resultarray=np.subtract(array1,array2)
print("\nUsing Numpy Function:\n",resultarray)


using operator:
 [[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]

Using Numpy Function:
 [[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]


In [ ]:
array2=np.array([[11,12,13],[14,15,16],17,18,19])
print(array2)

In [ ]:
resultarray=array1+array2
print("\nusing operator:\n",resultarray)
resultarray=np.add(array1,array2)
print("\nUsing Numpy Function:\n",resultarray)


using operator:
 [[12 14 16]
 [18 20 22]
 [24 26 28]]

Using Numpy Function:
 [[12 14 16]
 [18 20 22]
 [24 26 28]]


In [ ]:
resultarray=array1*array2
print("\nusing operator:\n",resultarray)
resultarray=np.multiply(array1,array2)
print("\nUsing Numpy Function:\n",resultarray)


using operator:
 [[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]

Using Numpy Function:
 [[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [ ]:
resultarray=array1/array2
print("\nusing operator:\n",resultarray)
resultarray=np.divide(array1,array2)
print("\nUsing Numpy Function:\n",resultarray)


using operator:
 [[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]

Using Numpy Function:
 [[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]


In [ ]:
resultarray=array1%array2
print("\nusing operator:\n",resultarray)
resultarray=np.mod(array1,array2)
print("\nUsing Numpy Function:\n",resultarray)


using operator:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Using Numpy Function:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
resultarray=np.transpose(array1)
print(resultarray)
#or
resultarray=array1.transpose
print(resultarray)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
<built-in method transpose of numpy.ndarray object at 0x7f4250a0eeb0>


In [ ]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

resultarray=np.dot(arr1,arr2)
print(resultarray)

32


In [ ]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

resultarray=np.hstack((arr1,arr2))
print(resultarray)

[1 2 3 4 5 6]


In [ ]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
resultarray=np.vstack((arr1,arr2))
resultarray

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
c=np.stack((array1,array2),axis=0)
print(c)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
#stacking 1 d arrays
c=np.stack((a,b),axis=0)

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
#stacking 1 d arrays
c=np.stack((a,b),axis=0)

In [ ]:
#stacking 3 d arrays with axis=0
c=np.stack((array1,array2),axis=0)
print(c)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]


In [ ]:
#stacking 3 d arrays with axis=1
c=np.stack((array1,array2),axis=1)
print(c)

[[[ 1  2  3]
  [11 12 13]]

 [[ 4  5  6]
  [14 15 16]]

 [[ 7  8  9]
  [17 18 19]]]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=20
print(arr)
print(x)

[20  2  3  4  5]
[1 2 3 4 5]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=20
print(arr)
print(x)

[20  2  3  4  5]
[20  2  3  4  5]


In [ ]:
import numpy as np
arr=np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [ ]:
import numpy as np
arr=np.array([20,21,22,24])
x=[True,False,False,True]
newarr=arr[x]
print(newarr)


[20 24]


In [ ]:
import numpy as np
arr=np.array([True,False,False,True])
print(np.sort(arr))


[False False  True  True]


In [ ]:
import numpy as np
arr=np.array([[10,20,30,12],[0,23,1,23]])
print(np.sort(arr))

[[10 12 20 30]
 [ 0  1 23 23]]


In [ ]:
import numpy as np
arr=np.array([2,3,1,4,5,5])
x=np.where(arr==5)
print(x)

(array([4, 5]),)


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7, 9]),)


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
x=np.where(arr%2==1)
print(x)

(array([0, 2, 4, 6, 8]),)


In [ ]:
#Reshape from 1-d to 2-d
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x=arr.reshape(4,3)
print(x)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#Reshape from 1-d to 3-d
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x=arr.reshape(2,3,2)
print(x)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
import numpy as np
b = np.arange(50,0,-1).reshape(5,10)

print(b)


[[50 49 48 47 46 45 44 43 42 41]
 [40 39 38 37 36 35 34 33 32 31]
 [30 29 28 27 26 25 24 23 22 21]
 [20 19 18 17 16 15 14 13 12 11]
 [10  9  8  7  6  5  4  3  2  1]]


In [ ]:
import numpy as np
b = np.arange(50,0,-1)

print(b)

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1]


In [ ]:
import numpy as np
list1=[x for x in range(0,101,2)]

a = np.array(list1)
print(a)
print(type(list1))
print(type(a))

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
nparray=np.empty((3,3),int)
nparray

array([[67135200,        0,        0],
       [       0,        0,        0],
       [       0,        0,       96]])

In [ ]:
z = np.linspace(0,100,5)
print(z)

[  0.  25.  50.  75. 100.]


In [ ]:
import numpy as np
arr = np.array([10,20,30,4,50,4,4])
x = np.where(arr==4)
print(x)

(array([3, 5, 6]),)


In [ ]:
import numpy as np
arr = np.array([6,7,8,9])

x = np.searchsorted(arr,7)

print(x)

1


In [ ]:
import numpy as np
arr = np.array([6,7,8,9])

x = np.searchsorted(arr,7,side='right')

print(x)

2


In [ ]:
import numpy as np
arr = np.array([10,20,50,70])

x = np.searchsorted(arr, [20,40,60])
print(arr)
print(x)

[10 20 50 70]
[1 2 3]


In [ ]:
array1=np.array([1,2,3,12,5,7,0])
print(np.count_nonzero(array1))
print(np.nonzero(array1))
print(array1.size)

6
(array([0, 1, 2, 3, 4, 5]),)
7


In [ ]:
array1=np.array([1,2,3,4,5,6,7,8,9,9])
#standard deviation
print(np.std(array1))
#minimum
print(np.min(array1))
#summation
print(np.sum(array1))
#median
print(np.median(array1))
#mean
print(np.mean(array1))
#mode
from scipy import stats
print("Most Frequent element=",stats.mode(array1)[0])
print("Number of Occarances=",stats.mode(array1)[1])
#variance
print(np.var(array1))

In [ ]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [ ]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [ ]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [ ]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])
a + b


array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [ ]:
from numpy import array, argmin, sqrt, sum
observation = array([111.0, 188.0])
codes = array([[102.0, 203.0],
               [132.0, 193.0],
               [45.0, 155.0],
               [57.0, 173.0]])
diff = codes - observation    # the broadcast happens here
dist = sqrt(sum(diff**2,axis=-1))
argmin(dist)

0